const MoviesActionTypes = {
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_COLLECTIONS_SUCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
};

export default MoviesActionTypes;
